# Generated by Django 5.1.6 on 2025-02-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="", max_length=254, unique=True, verbose_name="email address"
            ),
            preserve_default=False,
        ),
    ]
