# Generated by Django 5.1.6 on 2026-04-27 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_commentmedia_file"),
        (
            "posts",
            "0010_rename_posts_bookm_owner_4740e8_idx_posts_bookm_owner_i_e104e2_idx_and_more",
        ),
        ("votes", "0004_alter_vote_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("owner", "post"), name="unique_user_post_vote"
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("owner", "comment"), name="unique_user_comment_vote"
            ),
        ),
    ]
