# Generated by Django 5.1.6 on 2025-04-27 17:13

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_defaults(apps, schema_editor):
    TopicCategory = apps.get_model('topics', 'TopicCategory')
    Topic = apps.get_model('topics', 'Topic')

    # Create categories
    art_category = TopicCategory.objects.create(name="Art", emoji="127912")
    bus_finance_category = TopicCategory.objects.create(name="Business & Finance", emoji="128181")
    ed_career_category = TopicCategory.objects.create(name="Education & Career", emoji="128218")
    food_drinks_category = TopicCategory.objects.create(name="Food & Drinks", emoji="127789")
    games_category = TopicCategory.objects.create(name="Games", emoji="128377")

    Topic.objects.bulk_create([
    # Food & Drinks
    Topic(name="Food & Recipies", category=food_drinks_category),
    Topic(name="Non-Alcoholic Beverages", category=food_drinks_category),
    Topic(name="Baking & Desserts", category=food_drinks_category),
    Topic(name="Barbecues & Grilling", category=food_drinks_category),
    Topic(name="Food industry & Restaurants", category=food_drinks_category),
    Topic(name="Vegetarian & Vegan Food", category=food_drinks_category),

    # Games
    Topic(name="Other Games", category=games_category),
    Topic(name="Gaming Consoles & Gear", category=games_category),
    Topic(name="Esports", category=games_category),
    Topic(name="Adventure Games", category=games_category),
    Topic(name="Gaming News & Discussion", category=games_category),
    Topic(name="Action Games", category=games_category),
    Topic(name="Strategy Games", category=games_category),
    Topic(name="Simulation Games", category=games_category),
    Topic(name="Role-Playing Games", category=games_category),
    Topic(name="Sports & Racing Games", category=games_category),

    # Business & Finance
    Topic(name="Personal Finance", category=bus_finance_category),
    Topic(name="Economics", category=bus_finance_category),
    Topic(name="Business News & Discussion", category=bus_finance_category),
    Topic(name="Deals & Marketplace", category=bus_finance_category),
    Topic(name="Startups & Entrepreneurship", category=bus_finance_category),
    Topic(name="Real Estate", category=bus_finance_category),

    # Art
    Topic(name="Peforming Arts", category=art_category),
    Topic(name="Architecture", category=art_category),
    Topic(name="Design", category=art_category),
    Topic(name="Art", category=art_category),
    Topic(name="Filmmaking", category=art_category),
    Topic(name="Digital Art", category=art_category),
    Topic(name="Photography", category=art_category),
])

    
def create_admin_user(apps, schema_editor):
    User = apps.get_model('accounts', 'User')  # replace with your custom user model if you have one

    User.objects.create(
        email='admin@admin.com',
        password=make_password('admin'),  # hashed password
        is_staff=True,
        is_superuser=True,
    )    


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_defaults),
        migrations.RunPython(create_admin_user),
    ]
