# Generated by Django 5.1.6 on 2025-03-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmedia",
            name="file",
            field=models.FileField(default="", upload_to="post_media/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="postmedia",
            name="type",
            field=models.CharField(blank=True, default="IMAGE", max_length=5),
        ),
    ]
