# Generated by Django 5.1.6 on 2025-03-17 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postmedia_file_alter_postmedia_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
