# Generated by Django 5.1.6 on 2025-04-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_post_flairs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={},
        ),
    ]
