# Generated by Django 5.1.6 on 2025-05-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='type',
            field=models.CharField(blank=True, choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('LINK', 'Link')], default='IMAGE', max_length=5),
        ),
    ]
