# Generated by Django 5.1.6 on 2025-05-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_recentlyviewedpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
