# Generated by Django 5.1.6 on 2026-04-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_bookmark"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bookmark",
            new_name="posts_bookm_owner_i_e104e2_idx",
            old_name="posts_bookm_owner_4740e8_idx",
        ),
        migrations.RenameIndex(
            model_name="bookmark",
            new_name="posts_bookm_post_id_4cac26_idx",
            old_name="posts_bookm_post_id_4c7f23_idx",
        ),
        migrations.AddField(
            model_name="post",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="vote_count",
            field=models.IntegerField(default=0),
        ),
    ]
