# Generated by Django 5.1.6 on 2026-05-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "posts",
            "0010_rename_posts_bookm_owner_4740e8_idx_posts_bookm_owner_i_e104e2_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="post_thumbnails"),
        ),
    ]
