# Generated by Django 5.1.6 on 2025-03-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_avatar_alter_profile_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
