# Generated by Django 5.1.6 on 2026-04-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_commentmedia_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="vote_count",
            field=models.IntegerField(default=0),
        ),
    ]
