# Generated by Django 5.1.6 on 2026-05-01 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0004_comment_vote_count"),
        (
            "posts",
            "0010_rename_posts_bookm_owner_4740e8_idx_posts_bookm_owner_i_e104e2_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="posts.post",
            ),
        ),
    ]
