# Generated by Django 5.1.6 on 2025-03-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'Communities'},
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
