# Generated by Django 5.1.6 on 2025-03-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_community_members_community_moderators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='rules',
            field=models.JSONField(default=list),
        ),
    ]
