# Generated by Django 5.1.6 on 2025-03-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_alter_community_moderators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='rules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
