# Generated by Django 5.1.6 on 2025-04-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_alter_community_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
