# Generated by Django 5.1.6 on 2025-04-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_community_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_mature',
            field=models.BooleanField(default=True),
        ),
    ]
