# Generated by Django 5.1.6 on 2025-04-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0009_community_is_mature"),
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="topics",
            field=models.ManyToManyField(to="topics.topic"),
        ),
    ]
