# Generated by Django 5.1.6 on 2025-04-14 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0010_community_topics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="moderators",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="communities_modding",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="type",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("restricted", "Restricted"),
                    ("private", "Private"),
                ],
                default="public",
            ),
        ),
    ]
